services:
    db:
        image: postgres
        container_name: postgres-finance
        restart: always
        environment:
            POSTGRES_DB: finance_db
            POSTGRES_USER: user
            POSTGRES_PASSWORD: financeSystem
        ports:
            - '5432:5432'
        volumes:
            - pgdata:/var/lib/postgresql/data

    backend:
        build:
            context: ./apps/backend-dotnet/FinanceSystem.API
        container_name: backend-finance
        restart: always
        depends_on:
            - db
        ports:
            - '3001:80'
        volumes:
            - ./apps/backend:/app
        command: npm run dev

volumes:
    pgdata:
