version: '3.8'

services:
    db:
        image: postgres
        container_name: postgres-finance
        restart: always
        environment:
            POSTGRES_DB: finance_db
            POSTGRES_USER: user
            POSTGRES_PASSWORD: financeSystem
        ports:
            - '5432:5432'
        volumes:
            - pgdata:/var/lib/postgresql/data

    app:
        container_name: finance-app
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        depends_on:
            - db
        ports:
            - '3001:8080'

volumes:
    pgdata:
