version: '3.8'

services:
    db:
        image: postgres
        container_name: postgres-finance
        restart: always
        environment:
            POSTGRES_DB: finance_db
            POSTGRES_USER: user
            POSTGRES_PASSWORD: financeSystem
        ports:
            - '5432:5432'
        volumes:
            - pgdata:/var/lib/postgresql/data

    backend:
        container_name: backend-finance
        build:
            context: ./apps/backend/FinanceSystem.API
        restart: always
        depends_on:
            - db
        ports:
            - '3001:80' # Porta 3001 da maquina, 80 no container

volumes:
    pgdata:
